branches:
  only:
    - master
    - dev

notifications:
        email: false
language: cpp

compiler:
  - g++
  - clang++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

addons:
  apt:
    packages:
    - libc6-dev
    - libc6
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libluajit-5.1-dev
    - libphysfs-dev
    - libopenal-dev
    - libmodplug-dev
    - libvorbis-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools		
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Wno-error -Wno-unused-parameter -Wl -Bsymbolic-functions .. && make && ctest -V

