branches:
  only:
    - master
    - dev

notifications:
        email: false
language: cpp

compiler:
  - g++
  - clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libc6-dev
    - libc6
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libluajit-5.1-dev
    - libphysfs-dev
    - libopenal-dev
    - libmodplug-dev
    - libvorbis-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools		
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Wno-error -Wno-unused-parameter -Wl -Bsymbolic-functions .. && make && ctest -V

